# Generated by Django 4.2.18 on 2025-03-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0002_alter_instrutor_codigo_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrutor',
            options={'ordering': ['id']},
        ),
    ]
