# Generated by Django 4.2.18 on 2025-03-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipodeatividade', '0003_alter_tipodeatividade_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodeatividade',
            options={'ordering': ['codigo']},
        ),
    ]
