# Generated by Django 4.2.18 on 2025-03-01 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0014_alter_aluno_data_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_inicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='Informe a data inicial de matrícula do Aluno'),
        ),
    ]
