# Generated by Django 4.2.18 on 2025-02-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='codigo',
            field=models.AutoField(help_text='Informe a descrição do Título', primary_key=True, serialize=False),
        ),
    ]
