# Generated by Django 4.2.18 on 2025-02-13 00:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipodeatividade', '0003_alter_tipodeatividade_codigo'),
        ('titulo', '0002_alter_titulo_codigo'),
        ('aluno', '0007_alter_aluno_data_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Informe a turma do Aluno', primary_key=True, serialize=False)),
                ('horario_aula', models.TimeField(help_text='Informe a hora em que a hora da aula da Turma')),
                ('data_inicial', models.DateField(default=datetime.datetime(2025, 2, 13, 0, 36, 21, 122086, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma')),
                ('data_final', models.DateField(default=datetime.datetime(2025, 2, 13, 0, 36, 21, 122086, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma')),
                ('codigo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipodeatividade.tipodeatividade')),
                ('codigo_titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulo.titulo')),
                ('matricula_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluno.aluno')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
