# Generated by Django 4.2.18 on 2025-02-13 00:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0001_initial'),
        ('turma', '0003_turma_duracao_aula_alter_turma_data_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='codigo_titulo',
        ),
        migrations.AddField(
            model_name='turma',
            name='id_instrutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instrutor.instrutor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 0, 50, 29, 376183, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 0, 50, 29, 376183, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma'),
        ),
    ]
