# Generated by Django 4.2.18 on 2025-02-15 00:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0014_alter_aluno_data_inicial'),
        ('turma', '0005_alter_turma_data_final_alter_turma_data_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 0, 28, 28, 569326, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 0, 28, 28, 569326, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma'),
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='data_inicio_matricula',
            field=models.DateField(default=datetime.datetime(2025, 2, 15, 0, 28, 28, 569326, tzinfo=datetime.timezone.utc), help_text='Data da matrícula do aluno na turma'),
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ausencia', models.DateField(default=datetime.datetime(2025, 2, 15, 0, 28, 28, 569326, tzinfo=datetime.timezone.utc), help_text='Data da falta do aluno na turma')),
                ('matricula_aluno', models.ForeignKey(help_text='Matrícula do aluno da turma', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('numero_turma', models.ForeignKey(help_text='Número da turma do aluno.', on_delete=django.db.models.deletion.CASCADE, to='turma.turma')),
            ],
        ),
    ]
