# Generated by Django 4.2.18 on 2025-03-02 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0015_alter_aluno_data_inicial'),
        ('instrutor', '0002_alter_instrutor_codigo_titulo'),
        ('turma', '0008_alter_ausencia_data_ausencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='id_instrutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrutores', to='instrutor.instrutor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='matricula_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='aluno.aluno'),
        ),
    ]
