# Generated by Django 4.2.18 on 2025-03-02 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipodeatividade', '0003_alter_tipodeatividade_codigo'),
        ('turma', '0011_alter_turmaaluno_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='tipodeatividade.tipodeatividade'),
        ),
    ]
