# Generated by Django 4.2.18 on 2025-03-03 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0015_alter_aluno_data_inicial'),
        ('turma', '0012_alter_turma_codigo_atividade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausencia',
            options={'ordering': ['numero_turma', 'matricula_aluno', 'id']},
        ),
        migrations.AlterModelOptions(
            name='turmaaluno',
            options={'ordering': ['numero_turma', 'matricula_aluno', 'id']},
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='matricula_aluno',
            field=models.ForeignKey(help_text='Matrícula do aluno da turma', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
        ),
    ]
