# Generated by Django 4.2.18 on 2025-03-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0014_alter_turmaaluno_matricula_aluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausencia',
            options={'ordering': ['numero_turma', 'matricula_aluno', 'data_ausencia', 'id']},
        ),
        migrations.AddConstraint(
            model_name='ausencia',
            constraint=models.UniqueConstraint(fields=('numero_turma', 'matricula_aluno', 'data_ausencia'), name='unique_ausencia_turma_aluno'),
        ),
        migrations.AddConstraint(
            model_name='turmaaluno',
            constraint=models.UniqueConstraint(fields=('numero_turma', 'matricula_aluno'), name='unique_turma_aluno'),
        ),
    ]
